# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f7b9d6d327b90acd746efa9f08db2d963f024fec6cd1c613fd9be521f530efa357f3de698cda21ae0a4a1e1e615231730d311f626707c1a4c68f9269668b0f

test:
  secret_key_base: 355e803883b413601a23bb78a629b726dadd2561937ba2d848c13873e43abf138213a0bd8bbad0e5c296364bc7e88395c0e971ac370458a422152a4d1f14b99f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
